version: '3'
services:
  icss-basis-front-plugin:
    image: nginx:latest
    ports:
      - "9601:80"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./storybook-static:/usr/share/nginx/html/
    container_name: icss-basis-front-plugin
    hostname: icss-basis-front-plugin

networks:
  icssui_net:
    external: true
